### ISSUE TITLE
Description for OnBroadcast() not correct

### ISSUE THREAD

**Issue by fe1t** [ClockworkSoul/smudge#19]
https://github.com/clockworksoul/smudge/blob/bd05cb5e09670a2735601a1992f9e9ca92dbfd1f/events.go#L34-L38

https://github.com/clockworksoul/smudge/blob/bd05cb5e09670a2735601a1992f9e9ca92dbfd1f/events.go#L60-L64

Both got the same descriptions which are OnChange().
Instead, the first one should be description of OnBroadcast().

**Comment by clockworksoul** [comment]
Oh, now that's just silly. Thanks for pointing that out!

I'll fix it while I'm in the code this weekend.

**Comment by clockworksoul** [comment]
All fixed. Thanks for finding that!
