### ISSUE TITLE
Any configuration to work with Smudge locally ?

### ISSUE THREAD

**Issue by fe1t** [ClockworkSoul/smudge#25]
I normally connect to university network and get public IP.

When I'm using Smudge for transmitting data (1000-1200 bytes/data), sometimes broadcast messages are lost or very slow.

So I'm here for an advice. I need Smudge to run and broadcast messages only in my localhost.

Here are some of my code.

```
func ConfigServer() error {
	port, err := strconv.Atoi(NODE_ID)
	if err != nil {
		return err
	}

	// Set configuration options
	smudge.SetListenIP(net.ParseIP(baseAddress))
	smudge.SetListenPort(port)
	smudge.SetHeartbeatMillis(500)
	smudge.SetMaxBroadcastBytes(2000)
	smudge.SetLogThreshold(smudge.LogOff)
	smudge.SetMulticastEnabled(false)
	smudge.SetClusterName("KU-Coin")

	smudge.AddStatusListener(MyStatusListener{})
	smudge.AddBroadcastListener(MyBroadcastListener{})

	// Add a new remote node. Currently, to join an existing cluster you must
	// add at least one of its healthy member nodes.

	if nodeAddress != knownNodes[0] {
		node, err := smudge.CreateNodeByAddress(knownNodes[0])
		if err == nil {
			smudge.AddNode(node)
		} else {
			return err
		}
	}

	// start the server
	go func() {
		smudge.Begin()
	}()

	// Handle SIGINT and SIGTERM.
	// quit := make(chan os.Signal, 2)
	// signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	// <-quit
	return nil
}
```

I've set baseAddress to "127.0.0.1" but still got no luck.

Thanks in advance

**Comment by eelcocramer** [comment]
I don't think you can broadcast messages that large. Max on IPv4 is 256 bytes as a broadcast message piggy bags on a single IPv4 frame. The other 256 bytes of the frame is used for Smudge signalling.

If you want to send larger messages you should split you message up in smaller bits and re-assemble them at the receiving side. Note that these smaller packages may be received out-of-order or may not be received at all.

**Comment by clockworksoul** [comment]
You could, in theory, increase the maximum packet size via `SetMaxBroadcastBytes(int)`, but this will also increase the UDP packet size, which isn't support by many infrastructures. They could be simply dropped and disappear into the void.

@eelcocramer is correct that for packets this large you may wish to split the messages into multiple parts that are re-assembled at the destination. This adds some administrative overhead on your part, but it's feasible.

Maybe, just maybe, a feature to support that automatically could be added directly into Smudge, but I can't promise it would be available any time soon.

If your network supports IPv6, you can also use that protocol to get a little more space to work with, if you can compress your messages to less than 512 bytes.

**Comment by fe1t** [comment]
I didn't deal the problem with splitting messages at the first place because I was aware of something that you said "Note that these smaller packages may be received out-of-order or may not be received at all."

The message out-of-order is not a big problem but the packet loss is very important to me.
According to 1000+ bytes of messages, I've used encoding/gob already. 
If you guys have any other good encoding. I'll be appreciated to test it.

I've heard about ETH encoding method called RLP. But I'm not sure how to get and plug in the module into my project.

Thanks!

**Comment by eelcocramer** [comment]
To be honest my remark about packet loss (or message loss) is an assumption which is based on the fact that messages or sent using ‘udp’ and that networks could split and merge during operation.

I noticed that smudge can deal with lost and reconnected links to some level. I think messages are send several times. This may depend on the load of the messages though. Maybe @clockworksoul can shine some light on how broadcasts propagate through the network?

**Comment by fe1t** [comment]
One more problem I found, I had 3 nodes that were in the same cluster and each nodes see others as ALIVE. Then, I disconnected 1 node and wait 4-5 seconds until other nodes found it as DEAD. Then, I rejoin this node into the cluster and wait until the other nodes found it as ALIVE and it knew those 2 nodes were ALIVE too. Then, I start broadcast messages. In this case, OnBroadcast() didn't trigger on those 2 nodes.

I've tried time.Sleep() after smudge.Begin() to make sure everything is ready to go. But the broadcasting still didn't work.

**Comment by fe1t** [comment]
I've done many experiments and come up with a assumption that any node that's online for a long time will rarely receive broadcast message from new joining nodes.

I set this assumption because when I join 2 new nodes at the same time and broadcast. those two can receive each other messages. But the one that's online for such 5 minutes can't receive any message but status.

**Comment by clockworksoul** [comment]
> I've done many experiments and come up with a assumption that any node that's online for a long time will rarely receive broadcast message from new joining nodes.

That's interesting... I'll start looking into that. Were you able to get broadcasts working at all?

**Comment by fe1t** [comment]
When I start node 1, then node 2, then node 3 continuously, everything worked fine.
But when I wait for like 3 minutes and disconnected node 3, then restart it. the broadcast messages from node 3 can't reach node 1 and node 2.
If I disconnected node 2 and node 3 after waiting 3 minutes, then restart those 2 nodes. The broadcast messages can reach each others but can't reach node 1.
I can give you my repo and shell script to reproduce it if you would like to.

Thanks!

**Comment by fe1t** [comment]
I've commited scripts file to use and README.md that includes step to reproduce

if you're interested...  
 https://github.com/fe1t/blockchain_programming_in_golang/blob/p2p_smudge/src/README.md

**Comment by fe1t** [comment]
I've commited scripts file to use and README.md that includes step to reproduce

if you're interested...
https://github.com/fe1t/blockchain_programming_in_golang/tree/p2p_smudge/src

**Comment by fe1t** [comment]
Any suggestion how to modify Smudge to handle TCP packet instead ?

Currently, I'm using Smudge as node discovery
When I want to broadcast a message, I just loop over AllNodes() and DialTCP on my own way.
This way seems pretty fast. but it has a problem when many goroutines trying to connect to same destination.
I'm not good at networking, so I don't know how to deal with this.

Thanks!

**Comment by clockworksoul** [comment]
Hi fe1t.

This package was constructed around UDP, and it's not a simple task to convert to TCP.

As we suggested above, however, you _could_ update the package to break up and reassemble packets (which is what TCP would be doing for you anyway). 

I'm sorry we can't help you further.

**Comment by fe1t** [comment]
Hi clockworksoul,

Don't worry, I've done it with atomic broadcast by using Smudge as node discovery protocol.

Thanks very much
