### ISSUE TITLE
Inefficient locking 

### ISSUE THREAD

**Issue by ayende** [ClockworkSoul/smudge#3]
In https://github.com/clockworksoul/smudge/blob/master/broadcast.go#L281 - you take a lock to see if the msg is already there, release the lock, and if it isn't (which is likely), take the same lock again.
Since the check you do outside the lock is very cheap, it is better to hold on to the lock and do the work in one shot.

**Comment by clockworksoul** [comment]
Point taken. I've made the appropriate changes. Thanks again.
