### ISSUE TITLE
Is this project still restricted to LAN?

### ISSUE THREAD

**Issue by munawarb** [ClockworkSoul/smudge#36]
I love this implementation and am currently in the process of writing C bindings for it. One question I have is this note in the documentation:
> No WAN support: only local-network, private IPs are supported.

Is this still true, despite there existing the ability to enter an IP (which can very well be public?) If so, what's restricting this program from supporting a WAN?

**Comment by eelcocramer** [comment]
I don’t think there is a technical limitation with the exception of multicast service discovery. Note there is security mechasism in place and anyone may join a cluster or send bogus messages that could result in all sorts of disasters.

**Comment by munawarb** [comment]
Great, thanks for your quick response.
