### ISSUE TITLE
Calling AddBroadcastListener is not thread safe

### ISSUE THREAD

**Issue by ayende** [ClockworkSoul/smudge#4]
It is possible that calling `AddBroadcastListener` from concurrent threads will cause it to lose the registration.
Reason: 
https://github.com/clockworksoul/smudge/blob/master/events.go#L36 is not protected.

**Comment by ayende** [comment]
Same for `AddStatusListener`

**Comment by clockworksoul** [comment]
Fixed and fixed. Thanks again!
