### ISSUE TITLE
Usage Query

### ISSUE THREAD

**Issue by beyondgrayzone** [ClockworkSoul/smudge#5]
Piece of code at the end of the README creates a listener at port 9999. My question is, where is this code located? On all member nodes? Or a separate server?

Thanks

**Comment by clockworksoul** [comment]
Hi NG,

This code is meant to be used as part of a large distributed application. The example would be compiled, and the resulting binary executed on each machine in the cluster.

**Comment by beyondgrayzone** [comment]
Hey, thanks a lot for clarifying.

**Comment by clockworksoul** [comment]
My pleasure. 🙂
