### ISSUE TITLE
Multicast discovery

### ISSUE THREAD

**Issue by Adirio** [ClockworkSoul/smudge#6]
It is listed in known issues, but is it planned?

**Comment by clockworksoul** [comment]
Hi Adirio,

I haven't spent much time looking at this project recently, but I've been looking for a reason to come back to it.

If it's something that you would find useful, I would be happy to implement it for you.

**Comment by Adirio** [comment]
That feature and IPv6 support, as I found while lookig at the code that only IPv4 support is provided, are two things that would be quite nice.

**Comment by clockworksoul** [comment]
Sounds good!

Would you mind creating a separate issue for IPv6 support?

Thanks!

**Comment by clockworksoul** [comment]
Taking a look at multicast support now.

**Comment by eelcocramer** [comment]
I'm wondering if multicast discovery should be left up to the application using smudge.

For example you could have 2 applications on a network that both use smudge to broadcast messages but should not connect to each others nodes as they do not share the same message model.

**Comment by clockworksoul** [comment]
It seems appropriate for Smudge to do as part of the discovery process, but you're right that we need some way to distinguish between multiple collections that happen to share the same network. 

Elasticsearch solves this problem by requiring that each cluster have a name/I'd set in each node by configuration, and announcements from nodes with a different name are simply ignored. 

Thoughts?

**Comment by eelcocramer** [comment]
That could work. That name should be replace `foobar` in the mdns example in this repo: https://github.com/hashicorp/mdns. 

I also think that multicast discovery should be optional.

**Comment by Adirio** [comment]
I agree, discovery options should be configurable: the user has the option to introduce some seeds him/herself or use multicast discovery by providing a namespace.

**Comment by clockworksoul** [comment]
Absolutely agree on all points.

I've almost got a working prototype together if you're interested (the issue6-multicast branch). Keep in mind that it's a feature-incomplete WIP though.

**Comment by Adirio** [comment]
membership.go lines 211-234:
```
func getMulticastAddress() string {
	if ipLen == net.IPv4len {
		if multicastAddress == "" {
			if ipLen == net.IPv6len {
				multicastAddress = defaultIPv6MulticastAddress
			} else if ipLen == net.IPv4len {
				multicastAddress = defaultIPv4MulticastAddress
			} else {
				logFatal("Failed to determine IPv4/IPv6")
			}
		}
	}

	return multicastAddress
}
```

You probably want to remove the outter `if ipLen == net.IPv4len` as it will not work properly for IPv6. You have the IP version check inside.

**Comment by clockworksoul** [comment]
Wait, what's that doing there? 😆 

Good catch. I have no idea what I was thinking.

**Comment by clockworksoul** [comment]
I created PR https://github.com/clockworksoul/smudge/pull/13 if you'd like to take a look at what I have.

If anybody wants to be a full-fledged collaborator so you can do proper code reviews, I'm certainly open to that as well. :)

**Comment by clockworksoul** [comment]
Merged https://github.com/clockworksoul/smudge/pull/13.
