### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Adirio** [ClockworkSoul/smudge#7]
Request for IPv6 support:

Some considerations:
- IPv6 does not modify UDP except for the checksum. In both cases, the UDP checksum adds the bytes of the source and target addresses, which in IPv6 are 4 times longer, but I'm quite sure that this field is calculated by the underlying UDP library, so this should not have an impact in Smudge.
- Transmitting IPv6 addresses inside the messages, however, does have an impact. There are two approaches to this. Use a flag that allows to distinguish IP versions and then use 4 or 16 bytes as necesary, or always use 16 bytes and embed the IPv4 in an IPv6 format (127.0.0.1 -> 7F.00.00.01 -> 0000:0000:0000:0000:0000:FFFF:7F00:0001 -> ::FFFF:7F00:1) what basically means using the last 4 bytes to store the IPv4 address and set all the bits of the 2 previous bytes. Golang's net.IP type will understand this addresses as IPv4.
- IPv6 increases the minimum message size that every implementation needs to subbort to 1280 bytes - 8 bytes for the UDP header - 40 bytes for the IPv6 header leaves 1232 bytes for the IPv6 extension headers plus the application payload. In IPv4 the maximum IP header is of 60 bytes and the UDP header 8 extra ones what makes the 576 minimum accepted package turn into 508 for the application.

**Comment by clockworksoul** [comment]
Resolved by https://github.com/clockworksoul/smudge/pull/10
