### ISSUE TITLE
Include node status change source in the gossip messages

### ISSUE THREAD

**Issue by Adirio** [ClockworkSoul/smudge#8]
The [SWIM document](https://www.cs.cornell.edu/~asdas/research/dsn02-swim.pdf) (section 4.2, page 6) defines the messages as:

- { Suspect M_j: M_i suspects M_j }
- { Alive M_j: M_l knows M_j is alive }
- { Confirm M_j: M_h declares M_j as faulty }

You are only passing the info of M_j (let's call it the target node) but you are not passing M_i/M_l/M_h (let's call it the source node). It may not seem to be needed but the source node is quite important. For example, when non-trustworthy nodes can be connected to the network. A mechanism for avoiding node impersonation would also be needed for this purpouse. Other examples of uses for the source address and port come to mind like prioritizing sending him an alive message so that the timeout doesn't proc, etc.

**Comment by clockworksoul** [comment]
Hi Adirio,

Thanks for pointing this out. You're absolutely right, currently the source node isn't being passed, but there are good reasons for it to do so.

Fortunately, this isn't a big change, but I won't have time to tackle it today. I hope to get to it this week.

Edit: classifying as a bug.

**Comment by clockworksoul** [comment]
Sorry to have put this off. It's a bigger change than I anticipated, but as a heads up I'm looking into this now.

**Comment by clockworksoul** [comment]
Closing as resolved by PR https://github.com/clockworksoul/smudge/pull/11
